name: Validate Repository Files

on:
  pull_request:
    branches:
      - main  # Trigger validation on pull requests to the main branch

jobs:
  validate:
    runs-on: ubuntu-22.04  # Use a specific version of Ubuntu

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure we fetch the full history to detect changes

      # Step 2: Get list of modified files
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v45
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            courses/**.yaml
            paths/**.yaml
            bootcamps/**.yaml
            faqs/**.yaml

      - name: List all changed files markdown files
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          
      # Step 3: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          pip install yamllint==1.30.0
          pip install PyYAML==6.0

      # Step 5: Validate Naming Convention
      - name: Validate Naming Convention
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          if [ -z "$ALL_CHANGED_FILES" ]; then
            echo "No YAML files modified."
          else
            python scripts/validate_naming.py $ALL_CHANGED_FILES
          fi

      # Step 6: Validate File Content
      - name: Validate File Content
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          if [ -z "$ALL_CHANGED_FILES" ]; then
            echo "No YAML files modified."
          else
            python scripts/validate_format.py $ALL_CHANGED_FILES
          fi
